AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-stepfunctions

  Sample SAM Template for aws-stepfunctions
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  EmailFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/email-function/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables:
          AWS_SESSION_TOKEN: ""
  
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EmailFunction:
    Description: "API Gateway endpoint URL for Email function"
    Value: !GetAtt EmailFunction.Arn

    
  
